version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y openjdk-11-jdk
      - apt-get install -y maven
      - pip install --upgrade awscli
      - cd 01api
      - aws cloudformation package --template-file petstore-api.yaml --s3-bucket bucketforpostmantesting --s3-prefix api-code --output-template-file petstore-api-output.yaml
  pre_build:
    commands:
      - echo MVN Clean started on `date` from dir `pwd`
      - mvn clean

  build:
    commands:
      - echo MVN accembly started on `date` from dir `pwd`
      - mvn package assembly:single
      - echo Build completed on `date` from dir `pwd`
  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN in template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json

artifacts:
  files:
    - target/local-groupon-web-service-1.1-jar-with-dependencies.jar
    - 01api/petstore-api-output.yaml
  #name: $(date +%Y-%m-%d)
  discard-paths: yes
